# Generated by Django 3.0.5 on 2020-06-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anagrafica',
        ),
    ]
