# Generated by Django 3.0.5 on 2020-06-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0002_delete_anagrafica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notizia',
            old_name='citta',
            new_name='comune',
        ),
    ]
