# Generated by Django 3.0.5 on 2020-05-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0002_auto_20200522_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notizia',
            old_name='text',
            new_name='description',
        ),
    ]
