# Generated by Django 3.0.5 on 2020-06-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0004_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoNotizia',
        ),
    ]
