# Generated by Django 3.0.5 on 2020-05-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_italiani', '0001_initial'),
        ('notizia', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='notizia',
            name='comune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.Comune'),
        ),
    ]
