# Generated by Django 3.0.5 on 2020-05-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_italiani', '0001_initial'),
        ('notizia', '0005_notizia_comune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notizia',
            name='comune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.Comune'),
        ),
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('citta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.Comune')),
            ],
        ),
    ]
