# Generated by Django 3.0.7 on 2020-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0006_notizia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notizia',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
