# Generated by Django 3.0.5 on 2020-05-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0006_auto_20200530_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notizia',
            old_name='comune',
            new_name='citta',
        ),
    ]
