# Generated by Django 3.0.7 on 2020-06-17 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0007_auto_20200616_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='notizia',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
