# Generated by Django 3.0.7 on 2020-06-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizia', '0008_notizia_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notizia',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
