# Generated by Django 3.0.5 on 2020-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('video', models.FileField(default='', upload_to='video/original')),
                ('video_480', models.FileField(blank=True, null=True, upload_to='video/mp4_480')),
                ('video_720', models.FileField(blank=True, null=True, upload_to='video/mp4_720')),
            ],
        ),
    ]
