# Generated by Django 3.0.5 on 2020-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='formato',
            field=models.CharField(choices=[('640', '640'), ('720', '1280'), ('1080', '1920')], default=720, max_length=4),
        ),
    ]
