# Generated by Django 3.0.5 on 2020-05-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20200511_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='logo',
            field=models.CharField(choices=[('SENZA', 'Senza'), ('CODIN', 'Codino')], default='LOGO', max_length=5),
        ),
    ]
