# Generated by Django 3.0.5 on 2020-05-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='logo',
            field=models.CharField(choices=[('SENZ', 'Senza'), ('LOGO', 'Logo')], default='LOGO', max_length=4),
        ),
    ]
